sudo: required

language: bash

dist: trusty

group: deprecated-2017Q4

services:
  - docker

env:
  - TRAVIS_SECURE_ENV_VARS=true

before_script:
  - docker pull ellerbrock/alpine-aliyuncli
  - docker run -e "ALICLOUD_ACCESS_KEY=${ALICLOUD_ACCESS_KEY}" -e "ALICLOUD_SECRET_KEY=${ALICLOUD_SECRET_KEY}" -e "ALICLOUD_REGION=${ALICLOUD_REGION}" ellerbrock/alpine-aliyuncli

notifications:
  email:
    on_success: never
    on_failure: always

